#
# Copyright (C) 2021-2022 Intel Corporation
# Copyright (C) CVAT.ai Corporation
#
# SPDX-License-Identifier: MIT
#

services:
  cvat_redis_sam:
    container_name: cvat_redis_sam
    image: redis:7.2-alpine
    restart: always
    command:
      - redis-server
      - --save
      - ""
      - --appendonly
      - "no"
      - --protected-mode
      - "no"
      - --maxmemory-policy
      - allkeys-lru
    volumes:
      - cvat_redis_sam_data:/data
    environment:
      - REDIS_DATABASES=1
      - REDIS_PASSWORD=
    networks:
      cvat:
        aliases:
          - cvat-redis-sam

volumes:
  cvat_redis_sam_data:
